CREATE TABLE gold.fct_credit (
    sk integer NOT NULL identity(1, 1) ENCODE raw
    distkey
,
        id integer ENCODE az64,
        sk_member integer ENCODE az64,
        sk_ownership integer ENCODE az64,
        sk_status integer ENCODE az64,
        sk_grade integer ENCODE az64,
        sk_payment integer ENCODE az64,
        loan_amnt real ENCODE raw,
        funded_amnt real ENCODE raw,
        funded_amnt_inv real ENCODE raw,
        term character varying(255) ENCODE lzo,
        int_rate real ENCODE raw,
        installment real ENCODE raw,
        issue_d date ENCODE az64,
        url character varying(255) ENCODE lzo,
        desc character varying(256) ENCODE lzo,
        purpose character varying(255) ENCODE lzo,
        title character varying(255) ENCODE lzo,
        dti real ENCODE raw,
        delinq_2yrs real ENCODE raw,
        earliest_cr_line date ENCODE az64,
        inq_last_6mths real ENCODE raw,
        mths_since_last_delinq real ENCODE raw,
        mths_since_last_record real ENCODE raw,
        open_acc real ENCODE raw,
        pub_rec real ENCODE raw,
        revol_bal real ENCODE raw,
        revol_util real ENCODE raw,
        total_acc real ENCODE raw,
        initial_list_status character varying(255) ENCODE lzo,
        out_prncp real ENCODE raw,
        out_prncp_inv real ENCODE raw,
        total_rec_prncp real ENCODE raw,
        total_rec_int real ENCODE raw,
        total_rec_late_fee real ENCODE raw,
        recoveries real ENCODE raw,
        collection_recovery_fee real ENCODE raw,
        last_credit_pull_d date ENCODE az64,
        collections_12_mths_ex_med integer ENCODE az64,
        mths_since_last_major_derog integer ENCODE az64,
        policy_code integer ENCODE az64,
        application_type character varying(255) ENCODE lzo,
        annual_inc_joint integer ENCODE az64,
        PRIMARY KEY (sk),
        FOREIGN KEY (sk_grade) REFERENCES gold.dim_grade(sk)
) DISTSTYLE AUTO
SORTKEY
    (sk);