INSERT INTO dev.gold.fct_credit 
(
    id, 
    sk_member, 
    sk_ownership, 
    sk_status, 
    sk_grade, 
    sk_payment, 
    loan_amnt,
    funded_amnt, 
    funded_amnt_inv, 
    term, 
    int_rate, 
    installment, 
    issue_d,
    url, 
    purpose, 
    title, 
    dti, 
    delinq_2yrs, 
    earliest_cr_line,
    inq_last_6mths, 
    mths_since_last_delinq, 
    mths_since_last_record,
    open_acc, 
    pub_rec, 
    revol_bal, 
    revol_util, 
    total_acc, 
    initial_list_status,
    out_prncp, 
    out_prncp_inv, 
    total_rec_prncp, 
    total_rec_int, 
    total_rec_late_fee,
    recoveries, 
    collection_recovery_fee, 
    last_credit_pull_d, 
    collections_12_mths_ex_med,
    mths_since_last_major_derog, 
    policy_code, 
    application_type, 
    annual_inc_joint
)
(
    SELECT 
        id, 
        (Select sk from dev.gold.dim_member where id=member_id and is_valid=True LIMIT 1),
        (SELECT sk FROM dev.gold.dim_ownership WHERE home_ownership = home_ownership LIMIT 1), 
        (SELECT sk FROM dev.gold.dim_status WHERE verification_status = verification_status and loan_status=loan_status LIMIT 1), 
        (SELECT sk FROM dev.gold.dim_grade WHERE grade=grade and sub_grade=sub_grade LIMIT 1), 
        (SELECT sk FROM dev.gold.dim_payment WHERE total_pymnt = total_pymnt 
        AND total_pymnt_inv = total_pymnt_inv AND last_pymnt_d = last_pymnt_d 
        AND last_pymnt_amnt = last_pymnt_amnt AND next_pymnt_d = next_pymnt_d LIMIT 1), 
        loan_amnt,
        funded_amnt, 
        funded_amnt_inv, 
        term, 
        int_rate, 
        installment, 
        issue_d,
        url,  
        purpose, 
        title, 
        dti, 
        delinq_2yrs, 
        earliest_cr_line,
        inq_last_6mths, 
        mths_since_last_delinq, 
        mths_since_last_record,
        open_acc, 
        pub_rec, 
        revol_bal, 
        revol_util, 
        total_acc, 
        initial_list_status,
        out_prncp, 
        out_prncp_inv, 
        total_rec_prncp, 
        total_rec_int, 
        total_rec_late_fee,
        recoveries, 
        collection_recovery_fee, 
        last_credit_pull_d, 
        collections_12_mths_ex_med,
        mths_since_last_major_derog, 
        policy_code, 
        application_type, 
        annual_inc_joint
    FROM dev.silver.loans
    WHERE id NOT IN (SELECT id FROM dev.gold.fct_credit)
);