
CREATE TABLE IF NOT EXISTS dev.silver.loans (
    sk bigint identity(1, 1),,
    id INTEGER,
    member_id INTEGER,
    loan_amnt REAL,
    funded_amnt REAL,
    funded_amnt_inv REAL,
    term VARCHAR(255), -- Assuming TEXT is similar to VARCHAR
    int_rate REAL,
    installment REAL,
    grade VARCHAR(255),
    sub_grade VARCHAR(255),
    emp_length VARCHAR(255),
    home_ownership VARCHAR(255),
    annual_inc REAL,
    --verification_status VARCHAR(255),
    issue_d DATE,
    loan_status VARCHAR(255),
    url VARCHAR(255),
    purpose VARCHAR(255),
    title VARCHAR(255),
    zip_code VARCHAR(255),
    addr_state VARCHAR(255),
    dti REAL,
    delinq_2yrs REAL,
    earliest_cr_line DATE,
    inq_last_6mths REAL,
    mths_since_last_delinq REAL,
    mths_since_last_record REAL,
    open_acc REAL,
    pub_rec REAL,
    revol_bal REAL,
    revol_util REAL,
    total_acc REAL,
    initial_list_status VARCHAR(255),
    out_prncp REAL,
    out_prncp_inv REAL,
    total_pymnt REAL,
    total_pymnt_inv REAL,
    total_rec_prncp REAL,
    total_rec_int REAL,
    total_rec_late_fee REAL,
    recoveries REAL,
    collection_recovery_fee REAL,
    last_pymnt_d DATE,
    last_pymnt_amnt REAL,
    next_pymnt_d DATE,
    last_credit_pull_d DATE,
    collections_12_mths_ex_med INTEGER,
    mths_since_last_major_derog INTEGER,
    policy_code INTEGER,
    application_type VARCHAR(255),
    annual_inc_joint INTEGER,
    inserted_time timestamp,
    updated_time timestamp,
    primary key(sk)
);


